name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
      - uses: actions/checkout@v2

      - name: Start Minikube
        uses: medyagh/setup-minikube@master

      - name: Check Cluster
        run: kubectl get pods -A

      - name: Build Docker Image inside Minikube
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -t devopshint/node-app:latest .
          echo "✅ Docker image built:"
          docker images | grep node-app

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s-node-app.yaml
          kubectl rollout status deployment/nodejs-app

      - name: Test service URLs
        run: |
          minikube service list
          echo "🔗 Access App:"
          minikube service nodejs-app --url
